server:
  port: 8761

eureka:
  instance:
    hostname: nswy-eureka
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    registerWithEureka: false
    fetchRegistry: false
spring.cloud.config.discovery.enabled: true

