spring:
      datasource:
        default:
              name: test_mysql
              url: jdbc:mysql://127.0.0.1:3306/nswy?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
              username: nswy
              password: 1234
              type: com.alibaba.druid.pool.DruidDataSource
              driver-class-name: com.mysql.jdbc.Driver
              # 连接池补充设置
              #初始化时建立物理连接的个数 最小 最大连接池数量
              initialSize: 10
              minIdle: 3
              maxActive: 15
              # 获取连接时最大等待时间，单位毫秒
              maxWait: 60000
              # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
              timeBetweenEvictionRunsMillis: 60000
              # 配置一个连接在池中最小生存的时间，单位是毫秒
              minEvictableIdleTimeMillis: 300000
              #用来检测连接是否有效的sql
              validationQuery: SELECT 1 FROM DUAL
              #执行validationQuery检测连接是否有效
              testWhileIdle: true
              testOnBorrow: false
              testOnReturn: false
              # 是否缓存preparedStatement 在mysql下建议关闭
              poolPreparedStatements: false
              maxPoolPreparedStatementPerConnectionSize: -1
              # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
              connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
              # 配置监控统计拦截的filters
              #filters: stat,wall,log4j2
              filters: stat,log4j2
              # 合并多个DruidDataSource的监控数据
              #useGlobalDataSourceStat: true
              loginUsername: nswy
              loginPassword: 1234

      redis:
        host: 47.92.108.227
        password: 123456
        port: 6379
        database: 0
        pool:
            max-active: 8
            max-wait: -1
            max-idle: 20000
            min-idle: 0
      timeout: 10000

springfox:
  name: 武汉光谷信息技术股份有限公司
  title: 农事无忧在线文档
  description: 农事无忧相关接口文档

feign :
  client:
   url: http://127.0.0.1:11100
