spring:
  application:
    name: nswy-im
#  cloud:
#    config:
#      enabled: true
#      uri: http://${http.config.uri}:8888
#      profile: ${http.config.profile}


  http:
    multipart:
      maxFileSize: 10Mb
      maxRequestSize: 10Mb

#http:
#  config:
#    uri: 127.0.0.1
#    profile: dev
  datasource:
    # 主数据源 默认的
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/relationship?useUnicode=true&characterEncoding=UTF-8
    username: relationship
    password: 1234
    # 连接池补充设置
    #初始化时建立物理连接的个数 最小 最大连接池数量
    initialSize: 10
    minIdle: 3
    maxActive: 15
    # 获取连接时最大等待时间，单位毫秒
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    #用来检测连接是否有效的sql
    validationQuery: SELECT 1 FROM DUAL
    #执行validationQuery检测连接是否有效
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 是否缓存preparedStatement 在mysql下建议关闭
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: -1
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 配置监控统计拦截的filters
    filters: stat,wall,log4j2
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true
    loginUsername: nswyim
    loginPassword: 1234

im:
  server:
    port: 30000

mybatis:
  type-aliases-package: com.ovit.**.pojo
  mapper-locations: classpath:mybatis/*.xml
  configuration:
    cache-enabled: false
    default-executor-type: reuse

#fastDFS
fdfs:
  conf: ./fdfs_client.conf
  http:
    uploadIp: 106.14.65.102